equalstodjango/equalsto/equalsto/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views import HomePageView, LoginView, LogOutView, SignUpView

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace='polls'), name='polls'),
    url(r'^admin/', admin.site.urls),
    # homepage
    url('^$', HomePageView.as_view(), name='home'),
    #sign up
    url(r'^accounts/register/$', SignUpView.as_view(), name='signup'),
    #setup login view
    url(r'^accounts/login/$', LoginView.as_view(), name='login'),
    #logout
    url(r'^accounts/logout/$', LogOutView.as_view(), name='logout'),   
]

equalstodjango/equalsto/polls/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
	# ex: /polls/
	url(r'^$', views.index, name='index'),
    	# ex: /polls/5/
    	url(r'^(?P<qNum>[0-9]+)/$', views.game, name='game'),
	url(r'^(?P<qNum>[0-9]+)/answered1/$', views.answered1, name='answered1'),
	url(r'^(?P<qNum>[0-9]+)/answered2/$', views.answered2, name='answered2'),
    	url(r'^results/$', views.results, name='results'),
]

equalstodjango/equalsto/polls/models.py
from django.db import models

#import user data model
from django.contrib.auth.models import User

#import these two so we can dynamically update our users table with current users
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.

class Question(models.Model):
	question_String = models.CharField(max_length=200)
	answer_1 = models.CharField(max_length=200)
	answer_2 = models.CharField(max_length=200)

"""
#onetoone field of users that makes sure there are no return errors when creating user attribute table
class tempUser(AbstractUser):
	def customer_profile(self):
		try:
			return self._customer_profile
		except CustomerProfile.DoesNotExist:
			return CustomerProfile.objects.create(user=self,)


class UserAttributes(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	"""

class Answer(models.Model):
	#connect answer to question
	#question = models.ForeignKey(Question, on_delete=models.CASCADE)
	#connect answer to user
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	#data holding quiz answers
	answer_1 = models.IntegerField(default = 0)
	answer_2 = models.IntegerField(default = 0)
	answer_3 = models.IntegerField(default = 0)
	answer_4 = models.IntegerField(default = 0)
	answer_5 = models.IntegerField(default = 0)
	answer_6 = models.IntegerField(default = 0)
	answer_7 = models.IntegerField(default = 0)
	answer_8 = models.IntegerField(default = 0)
	answer_9 = models.IntegerField(default = 0)
	answer_10 = models.IntegerField(default = 0)

"""Noah S was adding onetoonefield from user to answer,
in addition I had to migrate the DB because changing models
changes the db. got back to "no url to direct to" error which zack 
had fixed and I just hadnt gotten off of github yet. should work but
might need to rebuild database so answers instance gets created
correctly for every user :)
"""

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Answer.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.answer.save()
	
	#answer_text = models.CharField(max_length=200)
	#votes = models.IntegerField(default=0)
	

#create table that will mirror django's built in user table
#attach additional attributes here.

equalstodjango/equalsto/polls/forms.py
from django.contrib.auth.forms import UserCreationForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, ButtonHolder, Submit

from django.contrib.auth.forms import AuthenticationForm

class RegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'username',
            'password1',
            'password2',
            ButtonHolder(
                Submit('register', 'Register', css_class='btn-primary')
            )
        )

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'username',
            'password',
            ButtonHolder(
                Submit('login', 'Login', css_class='btn-primary')
            )
        )

equalstodjango/equalsto/polls/views.py
from __future__ import absolute_import
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Question
from .models import Answer


#apparently we can use render() as a shortcut instead of httpresponse. https://docs.djangoproject.com/en/1.10/intro/tutorial03/
#for more information

#display the template at polls/templates/polls/index.html
def index(request):
    	latest_question_list = Question.objects.order_by('-question_String')[:5]
    	context = {
        	'latest_question_list': latest_question_list,
    	}
    	return render(request, 'polls/index.html', context)

#play game
def game(request, qNum):
	currentQuestion = Question.objects.get(id = qNum)
	context = {
		'question': currentQuestion,
	}
	return render(request, 'polls/game.html', context)

def answered1(request, qNum):
	currentAnswer = get_object_or_404(Answer, user = request.user)
	whichAnswer = "answer_"+str(qNum)
	setattr(currentAnswer, whichAnswer, 1)
	currentAnswer.save()
	return HttpResponseRedirect(reverse('polls:index'))

def answered2(request, qNum):
	currentAnswer = get_object_or_404(Answer, user = request.user)
	whichAnswer = "answer_"+str(qNum)
	setattr(currentAnswer, whichAnswer, 2)
	currentAnswer.save()
	return HttpResponseRedirect(reverse('polls:index'))

def results(request):
	user_list = Answer.objects.all() #list of answers to compare
	currentUser = get_object_or_404(Answer, user = request.user) #find currently logged in user
	tempRelativeScore = 0
	highestScore = 0
	highestScoreUser = 0
	for x in range(len(user_list)):
		print (user_list[x])
		if (currentUser.answer_1 == user_list[x].answer_1):
			tempRelativeScore += 1
		if (currentUser.answer_2 == user_list[x].answer_2):
			tempRelativeScore += 1
		if (currentUser.answer_3 == user_list[x].answer_3):
			tempRelativeScore += 1
		if (currentUser.answer_4 == user_list[x].answer_4):
			tempRelativeScore += 1
		if (currentUser.answer_5 == user_list[x].answer_5):
			tempRelativeScore += 1
		if (currentUser.answer_6 == user_list[x].answer_6):
			tempRelativeScore += 1
		if (currentUser.answer_7 == user_list[x].answer_7):
			tempRelativeScore += 1
		if (currentUser.answer_8 == user_list[x].answer_8):
			tempRelativeScore += 1
		if (currentUser.answer_9 == user_list[x].answer_9):
			tempRelativeScore += 1
		if (currentUser.answer_10 == user_list[x].answer_10):
			tempRelativeScore += 1
		if (highestScore > tempRelativeScore):
			highestScore = tempRelativeScore
			highestScoreUser = x
	match = user_list[highestScoreUser].user
	#print out highestScoreUser
	return render(request, 'polls/results.html',{ "match_List": match })

equalstodjango/equalsto/polls/templates/polls/game.html
<!-- this is template for game -->

{% block content %}

{% load static %}

<html>

    <head>
        <title>EqualsTo</title>
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>

	<header id="logo">        
		<img src="http://i.imgur.com/cTSWWAu.png">
	</header>
    
        <div id="question">
            Would you rather...
        </div>
    
        <div id="buttons">
		<form action="{% url 'polls:answered1' question.id %}" method="post">
			{% csrf_token %}
			<button id="B1"> {{ question.answer_1 }} </button>
		</form>

		<form action="{% url 'polls:answered2' question.id %}" method="post">
			{% csrf_token %}
			<button id="B2"> {{ question.answer_2 }} </button>
		</form>
        </div>
        
    </header>

</html>

{% endblock content %}

equalstodjango/equalsto/polls/templates/polls/home.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>EqualsTo</h1>
<h2>Home</h2>
<img src="http://www.clker.com/cliparts/k/W/Z/5/C/q/equals-md.png">
<p>This is a test for the home page of teh Equals To site.</p>

equalstodjango/equalsto/polls/templates/polls/index.html
{% extends '_layouts/base.html' %}

<!-- this is template for index -->

{% block headline %}<h2>Choose which Question to Answer.</h2>{% endblock headline %}

{% block content %}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_String }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
	<style>
		#B {
			width: 300px;
			padding: 20px;
			cursor: pointer;
			font-weight: bold;
			font-size: 150%;
			border: 1px solid #3366cc;
			border-radius: 10px;
			box-shadow:: 6px 6px 5px #999;
		}
	</style>
	<form>
		<input id="B" type="button" value="Results" onclick="window.location.href='{% url 'polls:results' %}'"/>
	</form>

{% endblock content %}

equalstodjango/equalsto/polls/templates/polls/results.html
{% block content %}

{% load static %}
<html>

<head>
    <title>EqualsTo</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body id=home>
    <header id="logo">
        <img src="http://i.imgur.com/cTSWWAu.png">
    </header>
    
    <div id=info>
    
        <textarea id="matches" readonly>
            ZackSalama's Matches:

		"{{match_List}}"
        
                Stephen Hawking - 87%
                
                Dylan Schneider - 100%
                
                Cam Newton - 72%
        </textarea>
    
        <textarea id="profile" readonly>
            ZackSalama's Profile
        
            Name: Zack Salama
        
            Email: Zack.Salama@colorado.edu
        
            School: University of Colorado, Boulder
        
            Gender: Male
        
        
        </textarea>
        
    </div>

</body>

</html>
{% endblock %}